[workspace]
members = [
    "src/api",
    "egui-app"
]

[package]
name = "port-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29.0"
crossterm = "0.29.0"
procfs = "0.17.0"
nix = { version = "0.30.1", features = ["signal"] }
netstat2 = "0.11.2"

